apiVersion: v1
kind: Service
metadata:
  name: my-attu-svc
  labels:
    app: attu
spec:
  type: ClusterIP
  ports:
  - name: attu
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: attu
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-attu-ingress
spec:
  rules:
  - host: my-attu.local
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: my-attu-svc
              port:
                number: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-attu
  labels:
    app: attu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attu
  template:
    metadata:
      labels:
        app: attu
    spec:
      containers:
      - name: attu
        image: zilliz/attu:latest
        imagePullPolicy: Always
        ports:
        - name: attu
          containerPort: 3000
          protocol: TCP
        env:
        - name: HOST_URL
          value: http://my-attu.local