name: Attu docker build test

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Docker Build
        run: docker build -t zilliz/attu:dev --build-arg VERSION=dev .
