name: Attu dev release

on:
  pull_request_target:
    branches: [main]
    types: [closed]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Run server tests
      #   run: |
      #     cd server
      #     yarn install
      #     yarn test:cov

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v2
      #   with:
      #     # public repo needn't pass token
      #     # token: ${{ secrets.CODECOV_TOKEN }}
      #     # only upload server test coverage
      #     flags: server

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Docker Build&Push
        shell: bash
        run: |
          docker buildx build \
            --platform=linux/amd64,linux/arm64 \
            -t zilliz/attu:dev \
            --build-arg VERSION=dev \
            --push \
            --progress=plain \
            .
