name: Attu dev release

on:
  pull_request_target:
    branches: [main]
    types: [closed]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # - name: Run server tests
      #   run: |
      #     cd server
      #     yarn install
      #     yarn test:cov

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v2
      #   with:
      #     # public repo needn't pass token
      #     # token: ${{ secrets.CODECOV_TOKEN }}
      #     # only upload server test coverage
      #     flags: server

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Docker Build
        run: docker build -t zilliz/attu:dev --build-arg VERSION=dev .

      - name: Docker Push Dev
        run: docker push zilliz/attu:dev
