name: Attu dev release

on:
  pull_request_target:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Docker Build
        run: docker build -t zilliz/attu:dev --build-arg VERSION=dev .

      - name: Docker Push Dev
        run: docker push zilliz/attu:dev

  